version: "3.8"

services:
  node: # Node.js 프론트엔드
    build:
      context: ./node
      dockerfile: Dockerfile
    image: seoyoung1024/speech-feedback-service-node:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      - api
      - mongo

  api: # FastAPI 백엔드
    build:
      context: ./api
      dockerfile: Dockerfile
    image: seoyoung1024/speech-feedback-service-fastapi:latest
    ports:
      - "5000:5000"
    networks:
      - app-network
    # 환경변수는 .env 파일에서 로드
    env_file:
      - ./api/.env
    depends_on:
      - mongo
    command: ["/bin/sh", "-c", "printenv"] # 디버깅용

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
networks:
  app_network:
    driver: bridge
    
volumes:
  mongo_data: